declare namespace _default {
    const __init__: string[];
    const adaptiveLabelPositioningBehavior: (string | typeof AdaptiveLabelPositioningBehavior)[];
    const appendBehavior: (string | typeof AppendBehavior)[];
    const associationBehavior: (string | typeof AssociationBehavior)[];
    const attachEventBehavior: (string | typeof AttachEventBehavior)[];
    const boundaryEventBehavior: (string | typeof BoundaryEventBehavior)[];
    const rootElementReferenceBehavior: (string | typeof RootElementReferenceBehavior)[];
    const createBehavior: (string | typeof CreateBehavior)[];
    const fixHoverBehavior: (string | typeof FixHoverBehavior)[];
    const createDataObjectBehavior: (string | typeof CreateDataObjectBehavior)[];
    const createParticipantBehavior: (string | typeof CreateParticipantBehavior)[];
    const dataInputAssociationBehavior: (string | typeof DataInputAssociationBehavior)[];
    const dataStoreBehavior: (string | typeof DataStoreBehavior)[];
    const deleteLaneBehavior: (string | typeof DeleteLaneBehavior)[];
    const detachEventBehavior: (string | typeof DetachEventBehavior)[];
    const dropOnFlowBehavior: (string | typeof DropOnFlowBehavior)[];
    const eventBasedGatewayBehavior: (string | typeof EventBasedGatewayBehavior)[];
    const groupBehavior: (string | typeof GroupBehavior)[];
    const importDockingFix: (string | typeof ImportDockingFix)[];
    const isHorizontalFix: (string | typeof IsHorizontalFix)[];
    const labelBehavior: (string | typeof LabelBehavior)[];
    const messageFlowBehavior: (string | typeof MessageFlowBehavior)[];
    const modelingFeedback: (string | typeof ModelingFeedback)[];
    const replaceConnectionBehavior: (string | typeof ReplaceConnectionBehavior)[];
    const removeParticipantBehavior: (string | typeof RemoveParticipantBehavior)[];
    const replaceElementBehaviour: (string | typeof ReplaceElementBehaviour)[];
    const resizeBehavior: (string | typeof ResizeBehavior)[];
    const resizeLaneBehavior: (string | typeof ResizeLaneBehavior)[];
    const removeElementBehavior: (string | typeof RemoveElementBehavior)[];
    const toggleElementCollapseBehaviour: (string | typeof ToggleElementCollapseBehaviour)[];
    const spaceToolBehavior: (string | typeof SpaceToolBehavior)[];
    const subProcessStartEventBehavior: (string | typeof SubProcessStartEventBehavior)[];
    const unclaimIdBehavior: (string | typeof UnclaimIdBehavior)[];
    const updateFlowNodeRefsBehavior: (string | typeof UpdateFlowNodeRefsBehavior)[];
    const unsetDefaultFlowBehavior: (string | typeof UnsetDefaultFlowBehavior)[];
}
export default _default;
import AdaptiveLabelPositioningBehavior from "./AdaptiveLabelPositioningBehavior";
import AppendBehavior from "./AppendBehavior";
import AssociationBehavior from "./AssociationBehavior";
import AttachEventBehavior from "./AttachEventBehavior";
import BoundaryEventBehavior from "./BoundaryEventBehavior";
import RootElementReferenceBehavior from "./RootElementReferenceBehavior";
import CreateBehavior from "./CreateBehavior";
import FixHoverBehavior from "./FixHoverBehavior";
import CreateDataObjectBehavior from "./CreateDataObjectBehavior";
import CreateParticipantBehavior from "./CreateParticipantBehavior";
import DataInputAssociationBehavior from "./DataInputAssociationBehavior";
import DataStoreBehavior from "./DataStoreBehavior";
import DeleteLaneBehavior from "./DeleteLaneBehavior";
import DetachEventBehavior from "./DetachEventBehavior";
import DropOnFlowBehavior from "./DropOnFlowBehavior";
import EventBasedGatewayBehavior from "./EventBasedGatewayBehavior";
import GroupBehavior from "./GroupBehavior";
import ImportDockingFix from "./ImportDockingFix";
import IsHorizontalFix from "./IsHorizontalFix";
import LabelBehavior from "./LabelBehavior";
import MessageFlowBehavior from "./MessageFlowBehavior";
import ModelingFeedback from "./ModelingFeedback";
import ReplaceConnectionBehavior from "./ReplaceConnectionBehavior";
import RemoveParticipantBehavior from "./RemoveParticipantBehavior";
import ReplaceElementBehaviour from "./ReplaceElementBehaviour";
import ResizeBehavior from "./ResizeBehavior";
import ResizeLaneBehavior from "./ResizeLaneBehavior";
import RemoveElementBehavior from "./RemoveElementBehavior";
import ToggleElementCollapseBehaviour from "./ToggleElementCollapseBehaviour";
import SpaceToolBehavior from "./SpaceToolBehavior";
import SubProcessStartEventBehavior from "./SubProcessStartEventBehavior";
import UnclaimIdBehavior from "./UnclaimIdBehavior";
import UpdateFlowNodeRefsBehavior from "./UpdateFlowNodeRefsBehavior";
import UnsetDefaultFlowBehavior from "./UnsetDefaultFlowBehavior";
